#!/bin/bash

#   BAREOS® - Backup Archiving REcovery Open Sourced
#
#   Copyright (C) 2026-2026 Bareos GmbH & Co. KG
#
#   This program is Free Software; you can redistribute it and/or
#   modify it under the terms of version three of the GNU Affero General Public
#   License as published by the Free Software Foundation and included
#   in the file LICENSE.
#
#   This program is distributed in the hope that it will be useful, but
#   WITHOUT ANY WARRANTY; without even the implied warranty of
#   MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the GNU
#   Affero General Public License for more details.
#
#   You should have received a copy of the GNU Affero General Public License
#   along with this program; if not, write to the Free Software
#   Foundation, Inc., 51 Franklin Street, Fifth Floor, Boston, MA
#   02110-1301, USA.

# Upload outage shorter than flush_timeout (20 s against 120 s): the failed
# uploads are retried, the job ends OK and restores byte-identical.

set -e
set -o pipefail
set -u

TestName="$(basename "$(pwd)")"
export TestName

#shellcheck source=../../environment.in
. ./environment

#shellcheck source=../../scripts/functions
. "${BAREOS_SCRIPTS_DIR}"/functions

#shellcheck source=fault-functions
. ./fault-functions

start_test
setup_data
faults_clear

log="$tmp/short-outage.out"
rm -f "$log"
rm -rf "$RestoreDirectory"

cat <<END_OF_DATA >"$tmp/bconcmds"
@$out ${NULL_DEV}
messages
@$out $log
label volume=ShortOutage-0001 storage=dplcompat pool=ShortOutage
quit
END_OF_DATA
run_bconsole

fault_fail_uploads_for 20
cat <<END_OF_DATA >"$tmp/bconcmds"
@$out $log
run job=backup-short-outage yes
wait
messages
quit
END_OF_DATA
run_bconsole
jobid=$(queued_jobid "$log")
faults_clear

expect_termination "${jobid}" "Backup OK"
expect_not_grep "Failed to flush device" "$log" \
  "a flush failed although the outage was shorter than flush_timeout"
expect_grep "ShortOutage-0001.0000 failed " "${fault_dir}/upload.log" \
  "no upload failed, so the outage did not happen during the job"

cat <<END_OF_DATA >"$tmp/bconcmds"
@$out $log
restore jobid=${jobid} client=bareos-fd where=$RestoreDirectory all done yes
wait
messages
quit
END_OF_DATA
run_bconsole

expect_grep "Termination:.*Restore OK" "$log" "the restore did not end OK"
check_restore_diff "${BackupDirectory}"

end_test
